/* eslint-disable no-use-before-define */
/* eslint-disable quotes */
/* eslint-disable prefer-template */
/* eslint-disable no-unused-expressions */
/* eslint-disable space-unary-ops */
// @ts-ignore
import { GoogleSpreadsheet } from 'google-spreadsheet';
import _ from 'lodash';
import { MessageActionRow, Guild, ButtonInteraction, GuildMember, CommandInteraction } from 'discord.js';
import { DateTime } from 'luxon';
// @ts-ignore
import { createCommand } from '../../commands';
import { pick } from '../dmHandler/utils';
// @ts-ignore
import creds from '../../serverbot-google-credentials.json';
import { createButton } from '../reminderHandler/reminderHandler';

export const setupFlashCardCommands = (guild: Guild) => {
  // Initialize the sheet - doc ID is the long id in the sheets URL
  const funSurveySheet = new GoogleSpreadsheet('1TjDf9rHRPEJt59ZCApHnBF1KsKYm07O9889CgGTob7k');
  const docs = [funSurveySheet];

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  docs.forEach(async (doc) => {
    await doc.useServiceAccountAuth(
      // env var values are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      creds
    );
    await doc.loadInfo(); // loads document properties and worksheets
  });

  async function handleFlashCardAnswer(interaction: ButtonInteraction, answer: string, rightAnswer: string) {
    const isCorrect = answer === rightAnswer;

    let replyContent = ''
      + `\n\n  ${(interaction.member as GuildMember).nickname} ` + pick(['answered:', 'said:', 'put:'])
      + `\n  ${answer}...`;

    if (isCorrect) {
      replyContent += `\n  That is.... ` + pick(['Correct!!!', 'Right!', 'The right one!', 'True!']);
    } else {
      replyContent += `\n  That is.... ` + pick(['WRONG!!!', 'FALSE!!', 'The wrong one!', 'NOT right!!']);
      replyContent += `\n  The right answer is: "\n${rightAnswer}"`;
    }

    const newContent = (interaction.message as any).content + replyContent;
    (interaction.message as any).edit({
      content: newContent,
      components:
        [new MessageActionRow({
          components: [
            createButton({
              label: pick(['Again! 👏 👏 👏', 'Another!!', 'do it again!', 'One more please!']),
              style: 'PRIMARY',
              customId: `do-it-again-flashcard-${DateTime.now().toISO()}`,
              onPress: drawFlashCard
            })
          ]
        })]
    });
    await interaction.reply(replyContent);
    interaction.deleteReply();
  }

  async function drawFlashCard(interaction: ButtonInteraction | CommandInteraction) {
    const survey = pick(docs);
    const sheet = survey.sheetsByIndex[0];
    const rows = await sheet.getRows();
    const row = pick(rows) as any;

    const questions = Object.keys(row)
      .filter((key) => key[0] !== '_')
      .filter((key) => key !== 'Timestamp');
    const question = pick(questions.slice(1, -1));
    const name = row[questions[0]];
    const rightAnswer = row[question];
    let answers = [rightAnswer];
    _.shuffle(rows).forEach((row) => {
      const otherAnswer = row[question];
      if (answers.length >= 4) return;
      if (otherAnswer && !answers.includes(otherAnswer)) {
        answers.push(otherAnswer);
      }
    });
    const messageContent = '.'
      + `\n **${(interaction.member as GuildMember).nickname}** drew a flashcard!`
      + `\n What did ***${name}*** answer for this question?`
      + `\n    **${question}**`;
    interaction.reply({
      content: messageContent,
      components:
        [new MessageActionRow({
          components: answers.map((answer, index) => {
            const id = `flashCardAnswer-${index}${DateTime.now().toISO()}`;
            return createButton({
              label: `${answer}`.slice(0, 80),
              style: 'PRIMARY',
              customId: id,
              onPress: (interaction: ButtonInteraction) => handleFlashCardAnswer(interaction, answer, rightAnswer)
            });
          })
        })]
    });
  }

  createCommand(guild, {
    name: 'flashcard',
    description: 'Draw a flash card of pbc members survey answers',
    execute: drawFlashCard
  });
};
